language: swift
os: osx
osx_image: xcode10.2
env: SWIFT_SNAPSHOT=5.0.1

cache:
  directories:
    - cocoapods
podfile: ./Podfile

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - SCHEME=SegementSlide-Dynamic
    - SCHEME=SegementSlide-Dynamic-Tests
    - SCHEME=Example
    - SCHEME=ExampleTests

before_install:
  - gem install cocoapods -v '1.7.2'
  - pod repo update
  - pod install

script:
  - |
    set -o pipefail;
    if [ "$SCHEME" = SegementSlide-Dynamic ]; then
      xcodebuild clean test -project SegementSlide.xcodeproj -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = SegementSlide-Dynamic-Tests ]; then
      xcodebuild clean test -project SegementSlide.xcodeproj -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = Example ]; then
      xcodebuild clean test -workspace Example.xcworkspace -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    elif [ "$SCHEME" = ExampleTests ]; then
      xcodebuild clean test -workspace Example.xcworkspace -scheme "$SCHEME" -destination 'platform=iOS Simulator,name=iPhone X,OS=12.2' -configuration Release ONLY_ACTIVE_ARCH=YES -enableCodeCoverage YES | xcpretty -c;
    fi
  - pod lib lint --allow-warnings

after_success:
  - sleep 3
  - bash <(curl -s https://codecov.io/bash)